"""Rejudge frozen captures; preserve R1/R2 and record the float-overflow fix."""
import hashlib
import importlib.util
import json
from pathlib import Path
import subprocess
import sys

sys.dont_write_bytecode = True
root = Path(__file__).resolve().parent


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def save(name, value):
    with (root/name).open('x') as stream:
        stream.write(value)


paths = [root/name for name in ('judge.py', 'judge_v1.py', 'judge_r2.py', 'record_judge_r3.py',
         'requests.json', 'normal.stdout', 'ubsan.stdout',
         'drop_rest.stdout', 'fixed_margin.stdout')]
before = {path.name: sha(path) for path in paths}
commands = []
for case in ('normal', 'ubsan', 'drop_rest', 'fixed_margin'):
    for mode, flags in (('normal', []), ('optimized', ['-O'])):
        name = 'judge_r3_'+case+'_'+mode
        argv = [sys.executable, '-B', *flags, str(root/'judge.py'),
                str(root/'requests.json'), str(root/(case+'.stdout'))]
        result = subprocess.run(argv, capture_output=True, text=True,
                                check=False, timeout=30)
        save(name+'.stdout', result.stdout)
        save(name+'.stderr', result.stderr)
        expected = 1 if case in ('drop_rest', 'fixed_margin') else 0
        if result.returncode != expected:
            raise ValueError('unexpected R3 judge exit: '+name)
        commands.append(dict(name=name, argv=argv, exit_code=result.returncode,
                             expected_exit_code=expected))

spec = importlib.util.spec_from_file_location('relative_judge_r3', root/'judge.py')
judge = importlib.util.module_from_spec(spec)
spec.loader.exec_module(judge)
requests = judge.load((root/'requests.json').read_text())
answers = [judge.load(line) for line in (root/'normal.stdout').read_text().splitlines()]
probes = []
for constant in ('NaN', 'Infinity', '-Infinity', '1e999', '-1e999'):
    try:
        judge.load('{"ignored_extra":'+constant+'}')
    except ValueError as error:
        probes.append(dict(case=constant, refused=True, error=str(error)))
    else:
        raise ValueError('nonfinite constant admitted')
bad_ids = json.loads(json.dumps(requests))
bad_ids[0]['id'] = False
try:
    judge.judge(bad_ids, answers)
except ValueError as error:
    probes.append(dict(case='boolean_request_id', refused=True, error=str(error)))
else:
    raise ValueError('boolean request id admitted')
try:
    judge.load('{"op":"C","op":"C"}')
except ValueError as error:
    probes.append(dict(case='duplicate_key', refused=True, error=str(error)))
else:
    raise ValueError('duplicate key admitted')
after = {path.name: sha(path) for path in paths}
if before != after:
    raise ValueError('source/capture changed during R3 judgment')
spec2 = importlib.util.spec_from_file_location('relative_judge_r2_closed', root/'judge_r2.py')
previous = importlib.util.module_from_spec(spec2)
spec2.loader.exec_module(previous)
overflows_r2 = [previous.load('{"ignored_extra":'+number+'}')['ignored_extra']
                for number in ('1e999', '-1e999')]
if overflows_r2 != [float('inf'), -float('inf')]:
    raise ValueError('R2 overflow observation not reproduced')
record = dict(schema='mhgp10_relative_filter_judge_r3_v1', status='PASS',
              before=before, after=after, commands=commands, probes=probes,
              native_executions=0, GCP_used=False,
              r2_overflow_reproduced=['1e999 -> +inf', '-1e999 -> -inf'],
              trusted_panel='Frozen requests must also be hashed and regenerated by archive reader; optional exact_contact is not standalone input validation.')
save('judge_r3_execution.json', json.dumps(record, sort_keys=True, indent=2)+'\n')
print(json.dumps(dict(status='PASS', judgments=len(commands), probes=probes,
                      native_executions=0), sort_keys=True))
