#!/usr/bin/env python3
"""Rejudge the six archived v17 outputs against regenerated LiDAR inputs."""

import argparse
import hashlib
import json
import math
from pathlib import Path
import struct


HERE = Path(__file__).resolve().parent
BASE_LEVERS = (
    "atlas_saturate_deep", "q3_leaf_census", "q34_dead_lanes",
    "q34_witness_cache", "q34_dead_core", "tower_meb_proposal",
    "q34_jobs_by_mass", "q34_fine_jobs", "tower_overlap_static",
    "q2_jobs_by_mass",
)


def require(ok, reason):
    if not ok:
        raise ValueError(reason)


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def input_fnv(raw):
    require(len(raw) % 12 == 0, "incomplete u32le point")
    h = 14695981039346656037
    prime = 1099511628211
    for byte in (len(raw) // 12).to_bytes(8, "little"):
        h = ((h ^ byte) * prime) & ((1 << 64) - 1)
    for (value,) in struct.iter_unpack("<I", raw):
        require(value < (1 << 18), "coordinate outside u18")
        for byte in value.to_bytes(8, "little"):
            h = ((h ^ byte) * prime) & ((1 << 64) - 1)
    return f"{h:016x}"


def paired_equal(a, b, label):
    require(a == b, "engine/batch mismatch: " + label)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inputs", required=True, type=Path,
                        help="directory regenerated by the existing raw physical-sector generator")
    parser.add_argument("--probe", type=Path, help="optional live v17 binary to check against the receipt")
    parser.add_argument("--source", type=Path, help="optional live v17 source tree to check")
    args = parser.parse_args()
    receipt = json.loads((HERE / "receipt.json").read_text())
    require(receipt["schema"] == "mhgp9_audit_q34_batch_density_quarter_v1", "receipt schema")
    require(sha((args.inputs / "MANIFEST.json").read_bytes()) == receipt["input_manifest_sha256"],
            "source input manifest")
    if args.probe is not None:
        require(sha(args.probe.read_bytes()) == receipt["binary_sha256"], "probe binary changed")
    if args.source is not None:
        for name, expected in receipt["source_sha256"].items():
            require(sha((args.source / name).read_bytes()) == expected, "source changed: " + name)

    require(len(receipt["rows"]) == 6, "expected six paired rows")
    results = {}
    for row in receipt["rows"]:
        density, mode = row["density"], row["mode"]
        require(density in ("quarter", "half", "full") and mode in ("engine", "batch"), "row identity")
        require((density, mode) not in results, "duplicate row")
        raw = (args.inputs / row["input_file"]).read_bytes()
        require(sha(raw) == row["input_sha256"] and len(raw) == row["sites"] * 12, "input bytes")
        output_raw = (HERE / f"{density}_{mode}.stdout").read_bytes()
        require(sha(output_raw) == row["stdout_sha256"] and row["exit_code"] == 0, "archived process")
        require(row["stderr_sha256"] == sha(b""), "archived stderr was not empty")
        result = json.loads(output_raw)
        require(result["schema"] == "mhgp9_tower_probe_v17" and result["status"] == "complete_relative",
                "probe status/schema")
        require(result["input"] == {"format": "u32le", "grid": "1mm", "sites": row["sites"],
                                    "hash": input_fnv(raw)}, "probe input identity")
        expected_levers = {name: True for name in BASE_LEVERS}
        expected_levers.update(q34_batch_filter=mode == "batch", q34_gpu_filter=False)
        options = result["options"]
        require(options == {"K": 5, "K_effective": 5, "workers": 8, "s": 8,
                            "tower_static_threads": 8, "run_tower": True,
                            "levers": expected_levers}, "probe options")
        require(row["args"] == ["5", "8", "--s=8", "--static=8", "--grid=1mm",
                                 "--lever=q34_batch_filter=" + ("1" if mode == "batch" else "0"),
                                 "--lever=q34_gpu_filter=0"], "archived command")
        require([order["K"] for order in result["orders"]] == list(range(1, 6)), "missing order")
        work = result["ledger"]
        require(work["core_sites"] == work["dead_core_form_sites"] + 2 * work["dead_core_loads"],
                "all computed core forms")
        batch = result["q34_batch"]
        require(batch["used"] == (mode == "batch") and
                batch["backend"] == ("cpu" if mode == "batch" else "") and
                batch["device_ms"] == 0, "batch backend")
        if mode == "batch":
            require(batch["rectangles"] == work["q34_input_rectangles"] and
                    batch["survivors"] == work["core_builds"] and
                    work["witness_cache_queries"] == 0, "batch mass/visit identity")
        results[density, mode] = result

    for density in ("quarter", "half", "full"):
        engine, batch = results[density, "engine"], results[density, "batch"]
        for name in ("input", "orders", "tower_digest", "tower_work", "catalogue", "generator"):
            paired_equal(engine[name], batch[name], density + " " + name)
        for name in ("expanded_pairs", "core_builds", "core_sites", "dead_core_loads",
                     "dead_core_form_sites", "q3_edges", "q4_edges", "q3_seeds", "q4_seeds"):
            paired_equal(engine["ledger"][name], batch["ledger"][name], density + " " + name)

    rows = []
    for density in ("quarter", "half", "full"):
        e, b = results[density, "engine"], results[density, "batch"]
        rows.append((e["input"]["sites"], e["ledger"]["core_sites"]))
        print(f"{density}: n={e['input']['sites']} core_forms={e['ledger']['core_sites']} "
              f"CPU_engine/batch={e['chain_cpu_s']:.3f}/{b['chain_cpu_s']:.3f}s "
              f"witness_pair_visits={e['ledger']['witness_pair_node_visits']}/"
              f"{b['ledger']['witness_pair_node_visits']} "
              f"RSS_engine/batch={e['peak_rss_kb']}/{b['peak_rss_kb']}KiB")
    for a, b in zip(rows, rows[1:]):
        p = math.log(b[1] / a[1]) / math.log(b[0] / a[0])
        print(f"core_forms finite slope {a[0]}->{b[0]}: {p:.6f}")
    print("six archived v17 cases verified")


if __name__ == "__main__":
    main()
