#include <algorithm>
#include <array>
#include <bitset>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <tuple>
#include <set>
#include <vector>
using I=__int128_t;
struct P{uint32_t x,y,z;uint32_t operator[](int k)const{return k==0?x:k==1?y:z;}};
struct E{uint32_t a,b,F,mask;};
struct C{uint32_t g,h;};
struct Box{std::array<int64_t,3> lo,hi;};
struct N{int l,r,left=-1,right=-1,pivot=-1; Box A,B; std::array<uint64_t,4> collision{},pass3{},pass4{};};
template<class T>std::vector<T> read(const char*path){std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error(path);auto n=f.tellg();if(n%sizeof(T))throw std::runtime_error("size");std::vector<T>v(n/sizeof(T));f.seekg(0);f.read((char*)v.data(),n);return v;}
uint64_t norm(const std::array<int64_t,3>&v){return uint64_t(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);}
bool exact(const P&a,const P&b,const P&g,const P&h,int lane){
 std::array<int64_t,3>d{},wg{},wh{},u{};for(int k=0;k<3;++k){d[k]=int64_t(b[k])-a[k];wg[k]=2*int64_t(g[k])-a[k]-b[k];wh[k]=2*int64_t(h[k])-a[k]-b[k];u[k]=wg[k]+wh[k];}
 int64_t H=2*int64_t(norm(d))-int64_t(norm(wg))-int64_t(norm(wh));if(H<=0)return false;
 I X=0;for(int i=0;i<3;++i){int j=(i+1)%3,k=(i+2)%3;I v=I(d[j])*u[k]-I(d[k])*u[j];X+=v*v;}
 return lane==3?3*I(H)*H>4*X:I(H)*H>2*X;
}
// Exact extrema over the continuous product of six endpoint intervals for fixed g,h.
std::pair<int64_t,I> uniform(const Box&A,const Box&B,const P&g,const P&h){
 int64_t fmin=0;for(int i=0;i<3;++i){int64_t z=INT64_MAX;for(int ai=0;ai<2;++ai)for(int bi=0;bi<2;++bi){int64_t a=ai?A.hi[i]:A.lo[i],b=bi?B.hi[i]:B.lo[i];int64_t v=(int64_t(g[i])-a)*(b-int64_t(g[i]))+(int64_t(h[i])-a)*(b-int64_t(h[i]));z=std::min(z,v);}fmin+=z;}
 int64_t Hmin=4*fmin;if(Hmin<=0)return {Hmin,0};
 I Xmax=0;for(int i=0;i<3;++i){int j=(i+1)%3,k=(i+2)%3;int64_t mx=0;for(int aj=0;aj<2;++aj)for(int bj=0;bj<2;++bj)for(int ak=0;ak<2;++ak)for(int bk=0;bk<2;++bk){int64_t a_j=aj?A.hi[j]:A.lo[j],b_j=bj?B.hi[j]:B.lo[j],a_k=ak?A.hi[k]:A.lo[k],b_k=bk?B.hi[k]:B.lo[k];int64_t v=2*((b_j-a_j)*(int64_t(g[k])+h[k]-a_k-b_k)-(b_k-a_k)*(int64_t(g[j])+h[j]-a_j-b_j));mx=std::max(mx,std::abs(v));}Xmax+=I(mx)*mx;}
 return {Hmin,Xmax};
}
std::vector<E> edges;std::vector<P> pts;std::vector<uint8_t> present;std::vector<C> cand;std::vector<int> order;std::vector<N> nodes;std::vector<std::array<uint64_t,4>> guardbits;int leafcap;uint64_t tests=0,collisions=0,pass3nodes=0,pass4nodes=0,unif3edges=0,unif4edges=0,match_calls=0,match_iterations=0,validated_pairs=0;
int build(int l,int r){int id=nodes.size();nodes.push_back({});N&n=nodes.back();n.l=l;n.r=r;for(int k=0;k<3;++k){n.A.lo[k]=n.B.lo[k]=INT64_MAX;n.A.hi[k]=n.B.hi[k]=INT64_MIN;}for(int j=l;j<r;++j){auto e=edges[order[j]];for(int k=0;k<3;++k){int64_t a=pts[e.a][k],b=pts[e.b][k];n.A.lo[k]=std::min(n.A.lo[k],a);n.A.hi[k]=std::max(n.A.hi[k],a);n.B.lo[k]=std::min(n.B.lo[k],b);n.B.hi[k]=std::max(n.B.hi[k],b);}}
 if(r-l<=leafcap){n.pivot=order[(l+r)/2];return id;}
 int axis=0;int64_t width=-1;for(int k=0;k<6;++k){int64_t w=k<3?n.A.hi[k]-n.A.lo[k]:n.B.hi[k-3]-n.B.lo[k-3];if(w>width){width=w;axis=k;}}
 int m=(l+r)/2;std::nth_element(order.begin()+l,order.begin()+m,order.begin()+r,[&](int x,int y){auto ex=edges[x],ey=edges[y];uint32_t vx=pts[axis<3?ex.a:ex.b][axis%3],vy=pts[axis<3?ey.a:ey.b][axis%3];return vx==vy?x<y:vx<vy;});nodes[id].pivot=order[m];int left=build(l,m),right=build(m,r);nodes[id].left=left;nodes[id].right=right;return id;}
void walk(int id,int ci,bool inherit3,bool inherit4){if(inherit3&&inherit4)return;N&n=nodes[id];bool ok3=false,ok4=false;if(n.collision[ci/64]&(uint64_t(1)<<(ci%64))){++collisions;}else{++tests;auto [H,X]=uniform(n.A,n.B,pts[cand[ci].g],pts[cand[ci].h]);if(H>0){ok3=3*I(H)*H>4*X;ok4=I(H)*H>2*X;}
#ifdef VERIFY
 if(ok3||ok4){for(int jj=n.l;jj<n.r;++jj){auto e=edges[order[jj]];if(e.a==cand[ci].g||e.b==cand[ci].g||e.a==cand[ci].h||e.b==cand[ci].h||!exact(pts[e.a],pts[e.b],pts[cand[ci].g],pts[cand[ci].h],ok4?4:3))throw std::runtime_error("false uniform certificate");++validated_pairs;}}
#endif
 if(ok3&&!inherit3){n.pass3[ci/64]|=uint64_t(1)<<(ci%64);++pass3nodes;unif3edges+=n.r-n.l;}if(ok4&&!inherit4){n.pass4[ci/64]|=uint64_t(1)<<(ci%64);++pass4nodes;unif4edges+=n.r-n.l;}}
 bool p3=inherit3||ok3,p4=inherit4||ok4;if(n.left>=0){walk(n.left,ci,p3,p4);walk(n.right,ci,p3,p4);}}
void propagate(int id,const std::array<uint64_t,4>&p3,const std::array<uint64_t,4>&p4){N&n=nodes[id];for(int i=0;i<4;++i){n.pass3[i]|=p3[i];n.pass4[i]|=p4[i];}if(n.left>=0){auto a=n.pass3,b=n.pass4;propagate(n.left,a,b);propagate(n.right,a,b);}}
std::pair<bool,bool> match(const std::array<uint64_t,4>&p3,const std::array<uint64_t,4>&p4,uint32_t mask){++match_calls;std::array<uint32_t,8> used3{},used4{};int n3=0,n4=0;auto free=[&](std::array<uint32_t,8>&u,int n,C c){for(int i=0;i<n;++i)if(u[i]==c.g||u[i]==c.h)return false;u[n]=c.g;u[n+1]=c.h;return true;};for(size_t ci=0;ci<cand.size();++ci){++match_iterations;C c=cand[ci];if(n3<4&&(p3[ci/64]&(uint64_t(1)<<(ci%64)))&&free(used3,2*n3,c)){n3++;}if(n4<3&&(p4[ci/64]&(uint64_t(1)<<(ci%64)))&&free(used4,2*n4,c)){n4++;}if((!(mask&2)||n3>=4)&&(!(mask&4)||n4>=3))break;}return {!(mask&2)||n3>=4,!(mask&4)||n4>=3};}

struct Top {uint64_t q;uint32_t raw;};
struct Geo {std::array<int64_t,3>d,sm,A{},B{};uint64_t D;};
Geo geometry(P a,P b){Geo z{};for(int k=0;k<3;++k){z.d[k]=int64_t(b[k])-a[k];z.sm[k]=int64_t(b[k])+a[k];}z.D=norm(z.d);int main=0;for(int k=1;k<3;++k)if(std::abs(z.d[k])>std::abs(z.d[main]))main=k;int ia=(main+1)%3,ib=(main+2)%3;int64_t h=std::abs(z.d[main]),sg=z.d[main]>0?1:-1;z.A[ia]=h;z.A[main]=-sg*z.d[ia];z.B[ib]=h;z.B[main]=-sg*z.d[ib];return z;}
void collect_seed(int id,int depth,std::vector<int>&out){auto&n=nodes[id];if(depth==0||n.left<0){out.push_back(n.pivot);return;}collect_seed(n.left,depth-1,out);collect_seed(n.right,depth-1,out);}
void prepare_collision(int id){N&n=nodes[id];n.collision={};if(n.left<0){for(int j=n.l;j<n.r;++j){auto e=edges[order[j]];for(int k=0;k<4;++k)n.collision[k]|=guardbits[e.a][k]|guardbits[e.b][k];}}else{prepare_collision(n.left);prepare_collision(n.right);for(int k=0;k<4;++k)n.collision[k]=nodes[n.left].collision[k]|nodes[n.right].collision[k];}}
std::vector<C> palette(const std::vector<P>&ps,const std::vector<uint32_t>&ids,int depth){std::vector<int>seeds;collect_seed(0,depth,seeds);std::set<std::pair<uint32_t,uint32_t>> selected;uint64_t pair_tests_seed=0,inside_sites=0,top_sites=0;for(auto ei:seeds){auto e=edges[ei];Geo z=geometry(pts[e.a],pts[e.b]);std::array<std::vector<Top>,4> bins;for(size_t i=0;i<ps.size();++i){uint32_t raw=ids[i];if(raw==e.a||raw==e.b)continue;std::array<int64_t,3>w{};for(int k=0;k<3;++k)w[k]=2*int64_t(ps[i][k])-z.sm[k];uint64_t q=norm(w);if(q>z.D)continue;++inside_sites;int64_t da=0,db=0;for(int k=0;k<3;++k){da+=w[k]*z.A[k];db+=w[k]*z.B[k];}int quadrant=(int(da>=0)<<1)|int(db>=0);auto&bucket=bins[quadrant];auto it=std::lower_bound(bucket.begin(),bucket.end(),Top{q,raw},[](auto&a,auto&b){return std::tie(a.q,a.raw)<std::tie(b.q,b.raw);});if(bucket.size()==16&&it==bucket.end())continue;bucket.insert(it,{q,raw});if(bucket.size()>16)bucket.pop_back();}
 std::vector<uint32_t> chosen;for(auto&bucket:bins)for(auto c:bucket)chosen.push_back(c.raw);top_sites+=chosen.size();
 struct S {I margin;int i,j;uint32_t g,h;};std::array<std::vector<S>,2> scores;for(size_t i=0;i<chosen.size();++i)for(size_t j=i+1;j<chosen.size();++j){++pair_tests_seed;auto a=pts[e.a],b=pts[e.b],g=pts[chosen[i]],h=pts[chosen[j]];std::array<int64_t,3>d{},wg{},wh{},u{};for(int k=0;k<3;++k){d[k]=int64_t(b[k])-a[k];wg[k]=2*int64_t(g[k])-a[k]-b[k];wh[k]=2*int64_t(h[k])-a[k]-b[k];u[k]=wg[k]+wh[k];}int64_t H=2*int64_t(norm(d))-int64_t(norm(wg))-int64_t(norm(wh));if(H<=0)continue;I X=0;for(int k=0;k<3;++k){int l=(k+1)%3,m=(k+2)%3;I v=I(d[l])*u[m]-I(d[m])*u[l];X+=v*v;}I h2=I(H)*H;auto lo=std::min(chosen[i],chosen[j]),hi=std::max(chosen[i],chosen[j]);if(3*h2>4*X)scores[0].push_back({3*h2-4*X,int(i),int(j),lo,hi});if(h2>2*X)scores[1].push_back({h2-2*X,int(i),int(j),lo,hi});}
 for(int lane=0;lane<2;++lane){auto&v=scores[lane];std::sort(v.begin(),v.end(),[](auto&a,auto&b){if(a.margin!=b.margin)return a.margin>b.margin;return std::tie(a.g,a.h)<std::tie(b.g,b.h);});std::vector<bool>used(chosen.size());int take=lane==0?4:3;for(auto c:v){if(take==0)break;if(used[c.i]||used[c.j])continue;selected.emplace(c.g,c.h);used[c.i]=used[c.j]=true;--take;}}
 }
 std::cerr<<"seed_count "<<seeds.size()<<" cloud_scans "<<seeds.size()*ps.size()<<" inside_sites "<<inside_sites<<" top_sites "<<top_sites<<" pair_tests_seed "<<pair_tests_seed<<"\n";std::vector<C> out;for(auto [g,h]:selected){if(g>=h)throw std::runtime_error("palette guard identity");out.push_back({g,h});}return out;}
int main(int argc,char**argv){if(argc!=6)return 2;auto ps=read<P>(argv[1]);auto ids=read<uint32_t>(argv[2]);if(ps.size()!=123389||ps.size()!=ids.size())throw std::runtime_error("input count");auto mx=*std::max_element(ids.begin(),ids.end());pts.resize(size_t(mx)+1);present.resize(pts.size());for(size_t i=0;i<ps.size();++i){if(present[ids[i]]||ps[i].x>=(1U<<18)||ps[i].y>=(1U<<18)||ps[i].z>=(1U<<18))throw std::runtime_error("input identity/coordinate");present[ids[i]]=1;pts[ids[i]]=ps[i];}edges=read<E>(argv[3]);for(auto e:edges)if(e.a>=present.size()||e.b>=present.size()||!present[e.a]||!present[e.b]||e.F<2||(e.mask!=2&&e.mask!=4&&e.mask!=6))throw std::runtime_error("edge identity");std::string selection=argv[4];if(selection.rfind("seed:",0)!=0){std::ifstream in(argv[4]);uint32_t g,h;while(in>>g>>h){if(g>=h||h>=present.size()||!present[g]||!present[h])throw std::runtime_error("candidate guard identity");cand.push_back({g,h});}}leafcap=std::stoi(argv[5]);if(cand.size()>256||edges.size()!=67827)throw std::runtime_error("count");order.resize(edges.size());for(size_t i=0;i<order.size();++i)order[i]=i;auto t0=std::chrono::steady_clock::now();build(0,edges.size());auto tb=std::chrono::steady_clock::now();if(selection.rfind("seed:",0)==0){cand=palette(ps,ids,std::stoi(selection.substr(5)));}auto tp=std::chrono::steady_clock::now();if(cand.size()>256)throw std::runtime_error("candidate bitset capacity");guardbits.resize(pts.size());for(size_t ci=0;ci<cand.size();++ci){auto c=cand[ci];if(c.g>=guardbits.size()||c.h>=guardbits.size()||c.g==c.h||!present[c.g]||!present[c.h])throw std::runtime_error("guard ID");guardbits[c.g][ci/64]|=uint64_t(1)<<(ci%64);guardbits[c.h][ci/64]|=uint64_t(1)<<(ci%64);}prepare_collision(0);auto t1=std::chrono::steady_clock::now();for(size_t ci=0;ci<cand.size();++ci)walk(0,ci,false,false);auto t2=std::chrono::steady_clock::now();propagate(0,{},{});
 uint64_t closed=0,Fclosed=0,closed3=0,closed4=0,partial=0,failF=0;std::array<uint64_t,3> by_mask{},closed_by_mask{},F_by_mask{},Fclosed_by_mask{};std::vector<uint8_t> group_closed(edges.size());for(auto&n:nodes)if(n.left<0){std::array<uint64_t,3> count{},fsum{};for(int j=n.l;j<n.r;++j){auto e=edges[order[j]];int k=e.mask==2?0:e.mask==4?1:2;++count[k];fsum[k]+=e.F;}for(int k=0;k<3;++k)if(count[k]){by_mask[k]+=count[k];F_by_mask[k]+=fsum[k];uint32_t mask=k==0?2:k==1?4:6;auto [q3,q4]=match(n.pass3,n.pass4,mask);closed3+=count[k]*(q3&&(mask&2));closed4+=count[k]*(q4&&(mask&4));if(q3&&q4){closed+=count[k];Fclosed+=fsum[k];closed_by_mask[k]+=count[k];Fclosed_by_mask[k]+=fsum[k];for(int j=n.l;j<n.r;++j)if(edges[order[j]].mask==mask)group_closed[order[j]]=1;}else failF+=fsum[k];if(q3!=q4)partial+=count[k];}}auto t3=std::chrono::steady_clock::now();
 std::cerr<<"cand "<<cand.size()<<" nodes "<<nodes.size()<<" leaves "<<(nodes.size()+1)/2<<" bvh_build_us "<<std::chrono::duration_cast<std::chrono::microseconds>(tb-t0).count()<<" palette_us "<<std::chrono::duration_cast<std::chrono::microseconds>(tp-tb).count()<<" collision_us "<<std::chrono::duration_cast<std::chrono::microseconds>(t1-tp).count()<<" test_us "<<std::chrono::duration_cast<std::chrono::microseconds>(t2-t1).count()<<" group_match_us "<<std::chrono::duration_cast<std::chrono::microseconds>(t3-t2).count()<<" tests "<<tests<<" collision_skips "<<collisions<<" tile3 "<<pass3nodes<<" tile4 "<<pass4nodes<<" covered3 "<<unif3edges<<" covered4 "<<unif4edges<<" closed "<<closed<<" lane3_closed "<<closed3<<" lane4_closed "<<closed4<<" Fclosed "<<Fclosed<<" partial "<<partial<<" failF "<<failF<<" match_calls "<<match_calls<<" match_iterations "<<match_iterations<<" validated_pairs "<<validated_pairs<<"\n";std::cerr<<"masks counts "<<by_mask[0]<<" "<<by_mask[1]<<" "<<by_mask[2]<<" F "<<F_by_mask[0]<<" "<<F_by_mask[1]<<" "<<F_by_mask[2]<<" closed "<<closed_by_mask[0]<<" "<<closed_by_mask[1]<<" "<<closed_by_mask[2]<<" Fclosed "<<Fclosed_by_mask[0]<<" "<<Fclosed_by_mask[1]<<" "<<Fclosed_by_mask[2]<<"\n";
 // Pointwise oracle of this same, post-selected candidate palette.
 uint64_t pt_tests=0,point_closed=0,point_Fclosed=0,point3=0,point4=0,fallback_tests=0,fallback_closed=0,fallback_Fclosed=0,group_only=0;for(size_t ei=0;ei<edges.size();++ei){auto e=edges[ei];std::array<uint64_t,4>b3{},b4{};for(size_t ci=0;ci<cand.size();++ci){auto c=cand[ci];if(e.a==c.g||e.a==c.h||e.b==c.g||e.b==c.h)continue;++pt_tests;if(!group_closed[ei])++fallback_tests;bool q3=exact(pts[e.a],pts[e.b],pts[c.g],pts[c.h],3),q4=exact(pts[e.a],pts[e.b],pts[c.g],pts[c.h],4);if(q3)b3[ci/64]|=uint64_t(1)<<(ci%64);if(q4)b4[ci/64]|=uint64_t(1)<<(ci%64);}auto [q3,q4]=match(b3,b4,e.mask);point3+=q3&&(e.mask&2);point4+=q4&&(e.mask&4);if(q3&&q4){point_closed++;point_Fclosed+=e.F;if(!group_closed[ei]){++fallback_closed;fallback_Fclosed+=e.F;}}else if(group_closed[ei])++group_only;}
 auto t4=std::chrono::steady_clock::now();std::cerr<<"point_tests "<<pt_tests<<" pointwise_us "<<std::chrono::duration_cast<std::chrono::microseconds>(t4-t3).count()<<" point_closed "<<point_closed<<" point_Fclosed "<<point_Fclosed<<" point3 "<<point3<<" point4 "<<point4<<" fallback_tests "<<fallback_tests<<" fallback_closed "<<fallback_closed<<" fallback_Fclosed "<<fallback_Fclosed<<" group_only "<<group_only<<"\n";
}
