#!/usr/bin/env python3
"""Counted mechanical extraction of a native Builder; never edits src/."""
import difflib
import hashlib
import json
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parents[1] / 'src/tower/forest/full_ball_tower.hpp'
EXPECTED = '124d3e9b52b1e6155e5a2ffd2a32cda7e5b403dda21155da2949b9ca8c90c0d0'


def transformed():
    raw = SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != EXPECTED:
        raise RuntimeError('native Builder source changed')
    text = raw.decode()
    begin, end = 'class Builder {\n', '\n};\n}  // namespace full_ball_detail\n\nnamespace full_ball_detail {\ninline FullBallTowerResult build_tower('
    if text.count(begin) != 1 or text.count(end) != 1:
        raise RuntimeError('extraction markers')
    original = text[text.index(begin):text.index(end)+4]
    edits = [
        ('class Builder {', 'class AObservedBuilder {'),
        ('  Builder(const CloudIndex& index,', '  AObservedBuilder(const CloudIndex& index,'),
        ('    order_prepare_lean(o);\n    reserve_lean(o);',
         '    order_prepare_lean(o);\n    ::mhgp9::audit::a_manifest::capture_a_input(o, program, balls, level_run, domain, ix);\n    reserve_lean(o);'),
        ('    block.contribution = o.lean_contribution[position];',
         '    ::mhgp9::audit::a_manifest::capture_a_roots(o.k, position, id, block.roots);\n    block.contribution = o.lean_contribution[position];'),
        ('    require(live == 1, "full_ball_final_component_count");\n    failpoint_after_lots(o.k);',
         '    require(live == 1, "full_ball_final_component_count");\n    ::mhgp9::audit::a_manifest::capture_a_output(o);\n    failpoint_after_lots(o.k);'),
    ]
    copied = original
    for old, new in edits:
        if copied.count(old) != 1:
            raise RuntimeError('substitution cardinality: ' + old)
        copied = copied.replace(old, new)
    header = ('#pragma once\n// Generated by instrument.py; source/patch pinned in instrument.json.\n'
              '#include "capture.hpp"\nnamespace mhgp9::tower::full_ball_detail {\n' + copied + '\n}\n')
    patch = ''.join(difflib.unified_diff(original.splitlines(True), copied.splitlines(True),
                                      fromfile='native::Builder', tofile='audit::AObservedBuilder'))
    meta = dict(source=str(SOURCE.relative_to(HERE.parents[2])), source_sha256=EXPECTED,
                original_class_sha256=hashlib.sha256(original.encode()).hexdigest(),
                generated_sha256=hashlib.sha256(header.encode()).hexdigest(),
                patch_sha256=hashlib.sha256(patch.encode()).hexdigest(), extraction_markers=2,
                renames=2, hooks=3, substitutions=[dict(before=a, after=b, count=1) for a, b in edits])
    return {'native_a.hpp': header, 'instrument.diff': patch, 'instrument.json': json.dumps(meta, indent=2, sort_keys=True)+'\n'}


def main():
    if sys.argv[1:] not in (['--write'], ['--check']):
        raise RuntimeError('usage: instrument.py --write|--check')
    files = transformed()
    for name, content in files.items():
        path = HERE / name
        if sys.argv[1] == '--write':
            if path.exists():
                raise RuntimeError('fresh generated file required: ' + name)
            path.write_text(content)
        elif path.read_text() != content:
            raise RuntimeError('generated file differs: ' + name)
    print(json.dumps(dict(status='PASS', renames=2, hooks=3, source_sha256=EXPECTED)))


if __name__ == '__main__':
    main()
