# Intrus entier exact — paquet privé du 11 septembre 2026

Primitive seulement, source active inchangée : minimiseurs entiers u16 sur device et premier intrus strict hors sélection, dans l'ordre du résolveur FULL CPU (gauche d'abord, ranges croissants). Aucun terminal complet ni contrat 50k/multi-millions n'est qualifié ici. `public_status=not_claimed`. GCP non utilisé pour ce paquet ; **aucune exécution device du nouveau helper**, même si les primitives arithmétiques réutilisées ont leurs propres preuves antérieures séparées.

Le juge O2 final et SAN ROOT compare 596 requêtes à un oracle Boost brut sur toutes les positions et au `intruder_work` CPU épinglé pour les quatre compteurs : 372 intrus, 224 absences, 34 points de coquille, 1 083 intérieurs sélectionnés exclus. Il vérifie aussi 175 cas d'axes et 700 boîtes par énumération exhaustive de la grille. Au total : 6 861 contrôles, 19 rejets requête/vue, 13 rejets propriétaire/génération. La pile de 49 références est atteinte sur un peigne Morton de 48 bits. Les tests de puissance historiques restent nuls sur les feuilles, conséquence exacte de bornes égales et non vacuité cachée.

Le propriétaire hôte vérifie l'ordre Morton, les partitions des ranges, les références, les préfixes et les boîtes serrées ; il produit sa génération atomique non réutilisable avant épuisement. La génération protège contre une confusion de propriétaires dans un processus, pas contre des archives après redémarrage, ni contre l'expiration des pointeurs. Il n'y a pas encore de route propriétaire CUDA produit. Les indices sont géométriques, pas des PointId ; une composition MEB doit trier une copie des sites sans changer les slots du support.

L'admission de puissance est $0<A<2^{68}$, $|B_i|<2^{87}$ et $|C|<2^{105}$. Ce profil couvre les lanes u16 mais n'est pas l'arithmétique de puissance i128 générale. La division signée générale est réutilisée depuis la primitive BallKey qualifiée ; aucun nouveau moteur de division. La primitive ne re-réduit pas la clé ni ne recertifie qu'une forme arbitraire est une MEB. Les formes algébriques limites sont des fixtures d'arithmétique.

Captures distinguées : O2 r1 pré-durcissement (609 cas) ; premier SAN ROOT r1 refusé à la compilation stricte d'une copie inutile dans une boucle de fixture ; O2 r2 et SAN ROOT r2 corrigés (612 attentes exportées). L'échec r1 est conservé avec ses sources, pas transformé en réussite. SAN hôte emploie ASan+UBSan et `detect_leaks=1`. Le TU autonome sans Boost est vérifié en O2, en SAN ROOT et après compilation/lien NVCC via `--host` uniquement. Le vrai `intruder_kernel` sm120 a 96 registres, une frame de 336 octets et zéro spill : propriétés du compilateur, pas mesures de vitesse GPU.

Six mutations C++ sont compilées et tuées causalement : mauvais arrondi, frontière non stricte, ordre inversé, exclusion oubliée, narrowing avant clipping, pile arbitraire de huit. Deux fautes de transport (sortie omise/corrompue) échouent sur `backend.expected_word`, pas seulement sur un contrôle final d'injection. Mauvais hash et arguments sont rejetés. Les six fautes du lecteur sont des mutants de métadonnées séparés, pas de nouvelles expériences C++.

Les fichiers sont dédupliqués par SHA-256 dans `objects/` ; `manifest.json` mappe leur nom logique. Aucun ELF ni vendor n'est distribué. Les hashes des binaires sont aussi relus après fermeture et explicitement identifiés comme tels ; ils ne sont ni une nouvelle exécution ni de nouveaux pins antérieurs. Le socle est `c03f6be8488453486b112811071827a96303ec86`, avec deux headers arithmétiques déjà qualifiés repris explicitement du prototype BallKey ; `current/baseline.json` donne les origines exactes.

Vérification : `python3 -B reader.py --selftest`, puis `python3 -B -O reader.py --selftest`. Le lecteur contrôle les hashes, sources avant/après, commandes et diagnostics causaux, planchers exacts, versions séparées et absence de claim GPU. Il ne recompile ni ne remplace l'oracle. Pour rejouer, matérialiser les fichiers `current/` dans un nouveau répertoire privé sous `build/`, puis utiliser le recorder sans écraser les captures : `python3 -B record.py --out nouveau --mode o2` ou `--mode san`. Les dépendances attendues sont le Boost local épinglé et le toolkit NVCC local, jamais embarqués ni téléchargés par ce paquet.

Gate autonome : `device_gate --selftest VECTORS --expected-sha=692d2105b551d464df537085afd5e610579555447df37ceb6991cfa541cf0145`. Une compilation g++ de `device_gate.cu` avec `-x c++ -DMHGP7_FAKE_DEVICE` est `host_stub` ; NVCC vise CUDA sm120 et n'exécute localement qu'avec `--host`. Une future exécution réelle exige une session G4 autorisée/gardée et une nouvelle capture. La gate compare 14 688 mots sur 612 cas, transporte explicitement les coefficients en dix mots u64, vérifie le layout et les octets des entrées relus, et exige neuf libérations CUDA explicites avant PASS.
