# Supplément privé : métadonnées des tours T2

Ce reçu ajoute deux gardes au juge T2 fermé, sans changer son résultat géométrique ni réécrire ses captures : l'ordre déclaré de chaque forêt doit correspondre à sa place K dans la tour ; son tableau vertical doit contenir exactement une entrée par nœud. Les sources actives et le dossier audits ne sont pas modifiés. `public_status=not_claimed`, GCP non utilisé, aucune compilation ou exécution GPU.

L'angle mort est confirmé avant de créditer sa fermeture. Une copie octet pour octet du juge publié passe `line12` avec chacun des deux mutants de source : K9 publié comme K8, puis une entrée verticale surnuméraire en K9. Chacun de ces témoins positifs de manque comporte 18 sorties réellement corrompues, signalées dans les logs, et conserve les compteurs du line12 antérieur. Ces 36 tours fautives ne sont pas des sorties conformes. Le juge renforcé, alimenté par exactement les mêmes headers mutants, les refuse ensuite respectivement sur `T2.metadata.order_identity` et `T2.metadata.vertical_node_indexed`, code 1, après la première sortie corrompue. Il n'y a ni bidouille mémoire ni faute seulement déclarée mais non exercée.

Les deux fautes vivent sous `MHGP7_T2_METADATA_MUTANT=1/2` dans des copies privées du constructeur de certificat et du constructeur de tour. Le nominal compile avec la valeur zéro. `t2_legacy_gate.cpp` reste identique au juge fermé ; seul `t2_gate.cpp` reçoit les deux gardes. Le diff complet est reproduit dans chaque capture, à partir des sources fermées également épinglées.

Le nouveau nominal rejoue line12, shell14 et spatial12 en O2 puis ASan/UBSan/LSan ROOT sur les mêmes sources. Par build : 54 tours K1..10, 540 ordres, 18 vrais census, 48 comparaisons physiques, 13 000 coupes et 8 103 948 vérifications verticales, comme auparavant. Les gardes s'appliquent une fois à chacun des 60 ordres des six références : 120 contrôles supplémentaires, soit 12 315 725 contrôles au total. Les 48 autres tours doivent être physiquement identiques à ces références contrôlées. Chaque sortie JSON nominale est exactement l'ancienne, sauf ces 40 contrôles ajoutés par géométrie. Les mutants sont exercés en O2 seulement ; aucun SAN mutant supplémentaire n'est revendiqué.

Le supplément ne rerun pas le différentiel de l'oracle historique ni les anciens mutants de géométrie ; leur reçu reste distinct et inchangé. Il n'étend pas la portée géométrique des trois fixtures, ne certifie pas K=n pour cette campagne n≥12/K≤10, ni la complétude WSPD universelle, ni un contrat de performance 50k ou multi-millions. Aucune preuve n'est automatiquement transférée à un nouveau résolveur CPU ou GPU.

Les objets sont dédupliqués par SHA-256, sans ELF ni vendor. `manifest.json` indique les chemins logiques, `closed/` contient les sources et sorties pertinentes du reçu antérieur, `current/` le nouvel arbre privé et `captures/` les commandes, sources avant/après, diagnostics et pins des binaires avant/après exécution. Les sources sont figées ; les répétitions créent de nouveaux répertoires.

Lecture seule : `python3 -B reader.py --selftest`, puis `python3 -B -O reader.py --selftest`. Le lecteur contrôle les sources, diffs, compteurs, marqueurs de fautes effectivement publiées, codes et diagnostics causaux, puis réfute cinq corruptions de métadonnées du reçu. Ces cinq tests du lecteur ne sont pas de nouvelles expériences C++. Pour reproduire, matérialiser `current/` dans un nouveau répertoire privé sous `build/`, conserver le reçu T2 parent au chemin déclaré et utiliser `record.py --out nouveau --mode causal`, `--mode o2`, puis `--mode san` en contexte ROOT avec LSan activé. Boost reste la dépendance de test locale, jamais distribuée avec le produit.
