# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile CXX with /usr/bin/g++
CXX_DEFINES = 

CXX_INCLUDES = -isystem /workspaces/E-HGP/build/v7_boost_gate/extracted/usr/include

CXX_FLAGS = -fsanitize=address,undefined -fno-omit-frame-pointer -fno-pie -O1 -g -DNDEBUG -std=c++20 -Wall -Wextra -Wpedantic -Werror

