# Porte a code de sortie exact : cmake -DEXPECTED=<code> -P run_expect.cmake -- <commande...>
# Le code obtenu doit etre exactement EXPECTED ; un crash par signal (texte au lieu d'un nombre) n'est jamais admis.
set(command)
set(seen_separator FALSE)
math(EXPR last "${CMAKE_ARGC} - 1")
foreach(i RANGE 0 ${last})
  if(seen_separator)
    list(APPEND command "${CMAKE_ARGV${i}}")
  elseif("${CMAKE_ARGV${i}}" STREQUAL "--")
    set(seen_separator TRUE)
  endif()
endforeach()
if(NOT command)
  message(FATAL_ERROR "run_expect : commande absente")
endif()
execute_process(COMMAND ${command} RESULT_VARIABLE code)
if(NOT code MATCHES "^[0-9]+$")
  message(FATAL_ERROR "run_expect : arret anormal (${code}) au lieu du code ${EXPECTED}")
endif()
if(NOT code EQUAL EXPECTED)
  message(FATAL_ERROR "run_expect : code ${code}, attendu ${EXPECTED}")
endif()
